feat: add image buttons, component
StickerStack/StickerStack_frontend pull request #171
Opened 2023-04-26 14:08 UTC by Anastacia-Tesli

2023-04-26 21:27 UTC, kivals requested changes

2023-04-26 21:27 UTC, kivals commented on src/components/ImagePick/ImagePick.module.scss
> +  background: url(../../images/bin.svg) no-repeat;
Можно отдельной задачей пройтись по всем SVG потом и оптимизировать их. Они ужмутся раза в 2.

2023-04-26 21:27 UTC, kivals commented on src/components/ImagePick/ImagePick.tsx
> +          <div className={styles.button_pen} />
Ниже похожий элемент (button_bin), можно вынести как компонент.
А почему не img? Это контентный элемент и можно использовать img с полезными аттрибутами типо alt

2023-04-26 21:27 UTC, kivals commented on src/components/ImagePick/ImagePick.module.scss
> +  border-radius: 20px;
наверное это лишнее.
у родителя:
```
border-radius: 10px;
overflow: hidden;
```

2023-04-27 05:39 UTC, HanmaDaiki commented on src/components/ImagePick/ImagePick.tsx
> +          <div className={styles.button_pen} />
Ну для компонента два повторяющихся элемента в одной и той же форме - это точно не то что нужно. Вот если бы такие иконки были бы еще где-то. А просмотрев фигму не нашёл подобного.
Я кстати так же как и Настя привык делать иконки в css, для чего alt? Чтобы потом было "Иконка редактировать Редактировать", как это поможет юзеру понять, что происходит? Мне кажется только запутает. Имхо div правильный выбор.

2023-04-27 05:39 UTC, HanmaDaiki commented on src/components/ProtectedRoute/ProtectedRoute.tsx
> +  if (isLogged) {
Да это она я так понимаю, делала чтобы верстать.

2023-04-27 06:23 UTC, Anastacia-Tesli commented on src/components/ImagePick/ImagePick.tsx
> +          <div className={styles.button_pen} />
Мне тоже кажется, что это НЕ контентное изображение. Не несет смысловой нагрузки, используется для оформления.

2023-04-27 06:34 UTC, Anastacia-Tesli commented on src/components/ProtectedRoute/ProtectedRoute.tsx
> +  if (isLogged) {
Спалила кухню

2023-04-27 07:28 UTC, kivals commented on src/components/ImagePick/ImagePick.tsx
> +          <div className={styles.button_pen} />
На мой взгляд такие плюсы:

+ дополнительные аттрибуты типо alt или title используются не только для SEO. Есть читалки с экрана (для слепых например). По этим тегам они понмают что сюда можно нажать.

+  семантика. + сразу взгляв на компонет понятно где тут иконка корзины. не надо идти в css.

+  lazy loading у img есть

+ картинки в img подгружаются через import - можно организовать единый реестр картинок в приложении - через компонент или просто модуль js/ts

Все это мелочи для нашего проекта. Просто хотел разобраться почему выбор пал на div. 
Против подхода на дивах ничего не имею.

2023-04-27 07:35 UTC, kivals approved these changes

2023-04-27 07:46 UTC, Anastacia-Tesli commented on src/components/ImagePick/ImagePick.tsx
> +          <div className={styles.button_pen} />
Как раз читалка с экрана действует следующим образом: начитывает по порядку все, что попадает в фокус. В фокус попадает кнопка целиком вместе с картинкой и текстом, текст зачитывается.

2023-04-27 07:54 UTC, merged