Feature/profile menu
StickerStack/StickerStack_frontend pull request #188
Opened 2023-05-03 07:23 UTC by d1sky

2023-05-03 08:14 UTC, Anastacia-Tesli commented on src/components/UI/ButtonCustom/ButtonCustom.module.scss
> +  &:focus,
Не совсем поняла зачем это, но наверное в целом про фокусы нужно будет отдельно поговорить и решить. Нас учили в целом визуально выделать фокусы на интерактивных элементах

2023-05-03 12:47 UTC, kivals requested changes

2023-05-03 12:47 UTC, kivals commented on src/components/Header/Header.tsx
> +  const [isMenuShow, setIsMenuShow] = useState(true)
А почему сразу активным делаем?

2023-05-03 12:47 UTC, kivals commented on src/components/ProfileMenu/ProfileMenu.tsx
> +// eslint-disable-next-line react/prop-types
Почему без интефейса пропсов?

2023-05-03 12:47 UTC, kivals commented on src/utils/useOutsideClick.tsx
> +                callback();
когда-нибудь этому callback может понадобится event-объект

2023-05-03 14:18 UTC, Anastacia-Tesli commented on src/components/Header/Header.tsx
> +        < ButtonCustom className={styles.profile} type='person' onClick={() => setIsMenuShow(true)} />
Думаю да

2023-05-03 14:27 UTC, d1sky commented on src/components/UI/ButtonCustom/ButtonCustom.module.scss
> +  &:focus,
Если нажать esc, то кнопка остается быть в фокусе, то есть присутствует обводка голубая. Код выше решает эту проблему

2023-05-03 14:43 UTC, Anastacia-Tesli commented on src/components/ProfileMenu/ProfileMenu.tsx
> +// eslint-disable-next-line react/prop-types
Потому что здесь пропсов вроде как нет?

2023-05-03 14:46 UTC, Anastacia-Tesli commented on src/components/ProfileMenu/ProfileMenu.tsx
> +// eslint-disable-next-line react/prop-types
А нет, есть ref, но наверное его можно не пробрасывать, а вызвать тут?

2023-05-03 14:53 UTC, HanmaDaiki commented on src/components/ProfileMenu/ProfileMenu.tsx
> +// eslint-disable-next-line react/prop-types
ref - это не пропс, он не типизируется. Есть же примеры. где мы используем forwardRef. Просто я так понимать тут props пустые, а указать надо, так как ref я так понимаю всегда на вторым идет

2023-05-03 14:56 UTC, HanmaDaiki commented on src/components/Header/Header.tsx
> +        < ButtonCustom className={styles.profile} type='person' onClick={() => setIsMenuShow(true)} />
Ага вместо тру логично будет !isMenuShow

2023-05-04 02:36 UTC, d1sky commented on src/components/Header/Header.tsx
> +  const [isMenuShow, setIsMenuShow] = useState(true)
Согласен, менял для отладки.

2023-05-04 02:40 UTC, d1sky commented on src/components/Header/Header.tsx
> +        < ButtonCustom className={styles.profile} type='person' onClick={() => setIsMenuShow(true)} />
Согласен, переделаю. Но на практике, мы никогда не сможем кликнуть на кнопку для закрытия меню.

2023-05-04 02:41 UTC, d1sky commented on src/components/ProfileMenu/ProfileMenu.module.scss
> +.menu {
Не работает или я не так делаю. Проблему решает, убрать у header   position: sticky;

2023-05-04 02:43 UTC, d1sky commented on src/utils/useOutsideClick.tsx
> +import { useEffect, useRef } from 'react';
+

2023-05-04 02:55 UTC, d1sky commented on src/components/ProfileMenu/ProfileMenu.tsx
> +const ProfileMenu = forwardRef<HTMLHeadingElement>((props, ref) => {
А где именно в макете подсмотреть? Он походу поменялся

2023-05-04 07:13 UTC, Anastacia-Tesli commented on src/components/ProfileMenu/ProfileMenu.tsx
> +                <Link to='/profile' className={styles.prfile_link}>
Если у меня в аккаунте не указаны имя и фамилия я не могу попасть в профиль, нажимать не на что 
![example](https://user-images.githubusercontent.com/107041912/236135307-4c7e2569-0f31-4bbe-a801-b3bfa1e6292a.png)

2023-05-04 07:14 UTC, Anastacia-Tesli commented on src/components/ProfileMenu/ProfileMenu.tsx
> +                        {`${lastName} ${firstName}`}
Сделай пожалуйста здесь отображение почты, если нет имени и фамилии

2023-05-04 07:16 UTC, HanmaDaiki commented on src/components/ProfileMenu/ProfileMenu.tsx
> +                <Link to='/profile' className={styles.prfile_link}>
Можно например, Профиль или Email, если нет ФИ

2023-05-04 07:16 UTC, Anastacia-Tesli commented on src/components/ProfileMenu/ProfileMenu.tsx
> +const ProfileMenu = forwardRef<HTMLHeadingElement>((props, ref) => {
![example](https://user-images.githubusercontent.com/107041912/236135875-cdd695f9-de63-4229-8dd2-92b441b46ec7.png)

2023-05-04 07:20 UTC, Anastacia-Tesli commented on src/components/ProfileMenu/ProfileMenu.tsx
> +                <Link to='/profile' className={styles.prfile_link}>
Почта

2023-05-04 07:21 UTC, Anastacia-Tesli commented on src/components/ProfileMenu/ProfileMenu.tsx
> +                <Link to='/profile' className={styles.prfile_link}>
Но вообще я бы это мини-изображение тоже сделала кликабельным вместе с текстом

2023-05-06 02:13 UTC, d1sky commented on src/components/ProfileMenu/ProfileMenu.tsx
> +                <Link to='/profile' className={styles.prfile_link}>
+

2023-05-06 02:27 UTC, d1sky commented on src/components/ProfileMenu/ProfileMenu.tsx
> +const ProfileMenu = forwardRef<HTMLHeadingElement>((props, ref) => {
Большие вопросы у меня. Может я не туда смотрю? @Anastacia-Tesli  не смог найти на макете этот пример. 108 отступ сверху относительно чего?

2023-05-06 02:39 UTC, d1sky commented on src/utils/useOutsideClick.tsx
> +                callback();
Правильно я понял, ты советуешь поменять на (event: Event) ? @kivals

2023-05-06 02:57 UTC, d1sky commented on src/utils/useOutsideClick.tsx
> +export const useOutsideClick = (callback: () => void) => {
проверил, ты прав

2023-05-06 02:57 UTC, d1sky commented on src/utils/useOutsideClick.tsx
> +                callback();
Поменял

2023-05-06 10:32 UTC, Anastacia-Tesli approved these changes

2023-05-06 10:37 UTC, merged