feat: add sticker card layout
StickerStack/StickerStack_frontend pull request #206
Opened 2023-05-10 15:22 UTC by Anastacia-Tesli

2023-05-10 16:26 UTC, HanmaDaiki commented on src/components/AddStickers/AddStickers.tsx
>      <div className={styles.container}>
Мне кажется тут все же должна быть форма. Мы разве тут уже не хотим использовать RHF - эти поля разви уже не валидируются?

2023-05-10 16:29 UTC, HanmaDaiki commented on src/components/AddStickers/AddStickers.module.scss
Я по CSS не спец и для меня все чисто.

2023-05-10 16:31 UTC, HanmaDaiki commented on src/components/UI/ButtonCustom/ButtonCustom.tsx
> +      aria-label={
А если увеличиться кол-во кнопочек? Будем этот тип расширять? По мне уж просто можно принять пропсом желаемый aria-label, за одно и от тернарника избавимся

2023-05-10 16:42 UTC, Anastacia-Tesli commented on src/components/UI/ButtonCustom/ButtonCustom.tsx
> +      aria-label={
Окей

2023-05-10 16:43 UTC, Anastacia-Tesli commented on src/components/AddStickers/AddStickers.tsx
>      <div className={styles.container}>
Это контейнер всей страницы, форма дальше

2023-05-10 16:43 UTC, Anastacia-Tesli commented on src/components/AddStickers/AddStickers.tsx
>      <div className={styles.container}>
По поводу унифицированного контейнера для секций писала вопрос

2023-05-10 20:18 UTC, kivals requested changes

2023-05-10 20:18 UTC, kivals commented on src/components/AddStickers/AddStickers.tsx
>  import { ButtonCustom, ButtonWithText, TitlePage } from '../UI';
Импорты неиспользуемые

2023-05-10 20:18 UTC, kivals commented on src/components/NewSticker/NewSticker.module.scss
> +  grid-template-rows: repeat(3, fit-content);
Мне кажется fit-content должен принимать параметры.

2023-05-10 20:23 UTC, Anastacia-Tesli commented on src/components/NewSticker/NewSticker.module.scss
> +.shapes {
У нас пока что нет адаптива, но можно в принципе и добавить 👍🏻

2023-05-10 20:25 UTC, Anastacia-Tesli commented on src/components/NewSticker/NewSticker.tsx
> +import rect_ronded from '../../images/rect-rounded.svg';
Недопустимое название?

2023-05-10 20:27 UTC, Anastacia-Tesli commented on src/components/NewSticker/NewSticker.module.scss
> +  grid-template-rows: repeat(3, fit-content);
minmax() принимает, по fit-content не знаю такого кейса

2023-05-11 07:11 UTC, kivals commented on src/components/NewSticker/NewSticker.tsx
> +import rect_ronded from '../../images/rect-rounded.svg';
не. Просто файл называется rect-rounded.svg, а импортируемое название rect_ronded - думал опечаталась.

2023-05-11 07:12 UTC, kivals commented on src/components/NewSticker/NewSticker.module.scss
> +.shapes {
Согласен, но 910px это даже не планшет еще

2023-05-11 07:14 UTC, kivals commented on src/components/NewSticker/NewSticker.module.scss
> +  grid-template-rows: repeat(3, fit-content);
https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content_function
тут написано, что должен. или что-то не то смотрю?

2023-05-11 07:32 UTC, Anastacia-Tesli commented on src/components/NewSticker/NewSticker.tsx
> +import rect_ronded from '../../images/rect-rounded.svg';
Нет, он же не допускает названия через дефис. Так назвать не получится )

2023-05-11 08:42 UTC, kivals approved these changes

2023-05-11 08:45 UTC, Anastacia-Tesli commented on src/components/NewSticker/NewSticker.module.scss
> +  grid-template-rows: repeat(3, fit-content);
Да, оказывается есть как свойство, так и такая функция. Но в контексте гридов походу именно функция, не знала 👍🏻

2023-05-11 08:54 UTC, merged