feat: show amount of stickers on preview
StickerStack/StickerStack_frontend pull request #270
Opened 2023-06-16 11:22 UTC by Anastacia-Tesli

2023-07-01 19:52 UTC, kivals requested changes

2023-07-01 19:52 UTC, kivals commented on src/components/NewSticker/NewSticker.tsx
> +    setAmount(number);
А зачем в этом компоненте своё состояние amount - если мы его получаем через пропсы?
И вообще должны ли мы на основе полученых пропсов заполнять поля формы? Например, если клиент заполнил все, потом сходил на другую страницу и вернулся.

2023-07-01 20:19 UTC, kivals requested changes

2023-07-01 20:19 UTC, kivals commented on src/components/NewSticker/NewSticker.tsx
> +                  onChange: (e) => {
а если просто ```onChange: handleAmountChange,  ```

2023-07-02 12:43 UTC, Anastacia-Tesli commented on src/components/NewSticker/NewSticker.tsx
> +  const handleAmountChange = (e: React.ChangeEvent<HTMLInputElement>) => {
Уже поправили и используем )

2023-07-02 20:00 UTC, kivals commented on src/components/NewSticker/NewSticker.tsx
> +                  onChange: (e) => {
я поменял и все работает. Предлагаю не тратить на это время. Оба варианта должны быть рабочими.

2023-07-02 20:03 UTC, kivals approved these changes

2023-07-02 20:03 UTC, kivals commented on src/store/cardsSlice.ts
> +      const indexCard = state.cards.find((card) => card.id === id);
indexCard - по сути это не индекс, а сам card.

2023-07-03 07:41 UTC, merged