fix: update styles
StickerStack/StickerStack_frontend pull request #288
Opened 2023-06-27 23:14 UTC by Anastacia-Tesli

2023-07-04 11:16 UTC, kivals requested changes

2023-07-04 11:16 UTC, kivals commented on src/components/pages/MainPage/MainPage.tsx
> +import { AnimatePresence, motion } from 'framer-motion';
В этом компоненте много неиспользованных импортов, обработчик - надо подчистить

2023-07-04 11:16 UTC, kivals commented on src/components/OurWorks/settings.tsx
> +import 'slick-carousel/slick/slick-theme.css';
эти импорты уже есть в OurWorks.tsx

2023-07-04 11:16 UTC, kivals commented on src/components/UI/TooltipCustom/TooltipCustom.tsx
> -      <IconButton
импорт остался

2023-07-05 10:55 UTC, HanmaDaiki approved these changes

2023-07-05 10:57 UTC, merged