api and popup slice reafctoring
StickerStack/StickerStack_frontend pull request #289
Opened 2023-06-28 12:02 UTC by HanmaDaiki

2023-06-28 17:26 UTC, Anastacia-Tesli approved these changes

2023-07-03 17:24 UTC, kivals requested changes

2023-07-03 17:24 UTC, kivals commented on src/store/popupSlice.ts
> +      if (localStorage.getItem('change-password-token')) {
На сколько мне известно, то эти функции должны быть "простыми" без "сайд эффектов".  А тут идет модификация стораджа

2023-07-03 17:24 UTC, kivals commented on src/components/MessagePopup/MessagePopup.tsx
> +      setTimeout(() => handleCloseMessage(), 2650);
Утечки памяти не будет? clearTimeout не нужен?

2023-07-03 17:24 UTC, kivals commented on src/components/pages/MainPage/MainPage.tsx
> +import { Signin } from '../../Popups/Signin/Signin';
порядок импортов

2023-07-05 05:47 UTC, closed without merging